# 1 - Twin Peaks Sentiment Analysis (SA)
This doc is a revision of my undergraduate dissertation and my introduction into data science.

Import libraries here.
```{r import-libraries, echo=FALSE, message=FALSE, warning=FALSE}
# Here are a bunch of libraries, we might not use.
library(dplyr)												
library(dplyr)											
library(readr)
library(tm) #Text mining
library(SnowballC) #Required for stemming
library(RColorBrewer) #Required for color palettes
library(ggplot2) #Required for plotting
library(wordcloud2)
```

Import the data.
```{r import-data, echo=FALSE, message=FALSE, warning=FALSE}
df <- 
  list.files(path = "C:/Users/markb/Documents/GitHub/twinpeaks-sa/src/data",
					pattern = "*.txt", 
					full.names = TRUE) %>%
lapply(read_csv) %>%										
bind_rows													

df %>% head()

```

Remove stop words.
```{r}
# import tidytext library
library(tidytext)
# create a var to hold unnested df
tidy_tp <- df %>%
  unnest_tokens(word, Text)
# check the head
tidy_tp %>%
  head()
```
```{r remove-stop-words}
# remove the stop words
tidy_tp <- tidy_tp %>% 
  anti_join(stop_words)

# check the head
tidy_tp %>%
  head()
```

Lets count the words
```{r}
tidy_tp %>%
  count(word, sort = TRUE) 

stop_words
```


```{r}
library(ggplot2)

tidy_tp %>%
  count(word, sort = TRUE) %>%
  filter(n > 600) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word)) +
  geom_col() +
  labs(y = NULL)
```

